=== cdevents/spec/custom/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://cdevents.dev/0.5.1/schema/custom",
  "properties": {
    "context": {
      "properties": {
        "specversion": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "string",
          "minLength": 1
        },
        "source": {
          "type": "string",
          "minLength": 1,
          "format": "uri-reference"
        },
        "type": {
          "type": "string",
          "pattern": "^dev\\.cdeventsx\\.[a-zA-Z0-9]+-[a-zA-Z]+\\.[a-zA-Z]+\\.[0-9]\\.[0-9]\\.[0-9]$"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "schemaUri": {
          "type": "string",
          "minLength": 1,
          "format": "uri"
        },
        "chainId": {
          "type": "string",
          "minLength": 1
        },
        "links": {
          "$ref": "links/embeddedlinksarray"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "specversion",
        "id",
        "source",
        "type",
        "timestamp"
      ]
    },
    "subject": {
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "source": {
          "type": "string",
          "minLength": 1,
          "format": "uri-reference"
        },
        "content": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "id",
        "content"
      ]
    },
    "customData": {
      "oneOf": [
        {
          "type": "object"
        },
        {
          "type": "string",
          "contentEncoding": "base64"
        }
      ]
    },
    "customDataContentType": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "type": "object",
  "required": [
    "context",
    "subject"
  ]
}

=== cdevents/spec/conformance/incident_reported.json
{
  "context": {
    "specversion": "0.5.1",
    "id": "F4BD2B55-B6F6-4F44-AF72-BD2D0E7A8708",
    "chainId": "4c8cb7dd-3448-41de-8768-eec704e2829b",
    "source": "/monitoring/prod1",
    "type": "dev.cdevents.incident.reported.0.3.0",
    "timestamp": "2022-11-11T13:52:20.079Z",
    "schemaUri": "https://myorg.com/schema/custom",
    "links": [
      {
        "linkType": "RELATION",
        "linkKind": "TRIGGER",
        "target": {
          "contextId": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
        },
        "tags": {
          "foo1": "bar",
          "foo2": "bar"
        }
      }, {
        "linkType": "PATH",
        "from": {
          "contextId": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
        },
        "tags": {
          "foo1": "bar",
          "foo2": "bar"
        }
      }, {
        "linkType": "END",
        "from": {
          "contextId": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
        },
        "tags": {
          "foo1": "bar",
          "foo2": "bar"
        }
      }
    ]
  },
  "subject": {
    "id": "incident-123",
    "source": "/monitoring/prod1",
    "content": {
      "description": "Response time above threshold of 100ms",
      "environment": {
        "id": "prod1",
        "source": "/iaas/geo1"
      },
      "service": {
        "id": "myApp",
        "source": "/clusterA/namespaceB"
      },
      "artifactId": "pkg:oci/myapp@sha256%3A0b31b1c02ff458ad9b7b81cbdf8f028bd54699fa151f221d1e8de6817db93427",
      "ticketURI": "https://my-issues.example/incidents/ticket-345"
    }
  },
  "customData": {
    "severity": "medium",
    "priority": "critical",
    "reportedBy": "userId"
  },
  "customDataContentType": "application/json"
}

=== cdevents/spec/conformance/incident_resolved.json
{
  "context": {
    "specversion": "0.5.1",
    "id": "F4BD2B55-B6F6-4F44-AF72-BD2D0E7A8708",
    "chainId": "4c8cb7dd-3448-41de-8768-eec704e2829b",
    "source": "/monitoring/prod1",
    "type": "dev.cdevents.incident.resolved.0.3.0",
    "timestamp": "2022-11-11T13:52:20.079Z",
    "schemaUri": "https://myorg.com/schema/custom",
    "links": [
      {
        "linkType": "RELATION",
        "linkKind": "TRIGGER",
        "target": {
          "contextId": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
        },
        "tags": {
          "foo1": "bar",
          "foo2": "bar"
        }
      }, {
        "linkType": "PATH",
        "from": {
          "contextId": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
        },
        "tags": {
          "foo1": "bar",
          "foo2": "bar"
        }
      }, {
        "linkType": "END",
        "from": {
          "contextId": "5328c37f-bb7e-4bb7-84ea-9f5f85e4a7ce"
        },
        "tags": {
          "foo1": "bar",
          "foo2": "bar"
        }
      }
    ]
  },
  "subject": {
    "id": "incident-123",
    "source": "/monitoring/prod1",
    "content": {
      "description": "Response time restored below 100ms",
      "environment": {
        "id": "prod1",
        "source": "/iaas/geo1"
      },
      "service": {
        "id": "myApp",
        "source": "/clusterA/namespaceB"
      },
      "artifactId": "pkg:oci/myapp@sha256%3A0b31b1c02ff458ad9b7b81cbdf8f028bd54699fa151f221d1e8de6817db93439"
    }
  },
  "customData": {
    "metric": "responseTime",
    "threshold": "100ms",
    "value": "70ms"
  },
  "customDataContentType": "application/json"
}
